# Generated by Django 5.2.15 on 2026-06-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invocationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTaskMainTask',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_category', models.CharField(default='申请处理', max_length=80)),
                ('product', models.CharField(default='产品A', max_length=80)),
                ('owner', models.CharField(blank=True, default='', max_length=80)),
                ('environment', models.CharField(default='环境1', max_length=80)),
                ('origin', models.CharField(default='产地1', max_length=80)),
                ('region', models.CharField(default='地区1', max_length=80)),
                ('city', models.CharField(default='城市1', max_length=80)),
                ('apply_count', models.IntegerField(default=0)),
                ('patch_count', models.IntegerField(default=0)),
                ('approve_count', models.IntegerField(default=0)),
                ('priority', models.CharField(default='中', max_length=20)),
                ('status', models.CharField(default='未提交', max_length=40)),
                ('due_date', models.CharField(blank=True, default='', max_length=20)),
                ('completion', models.PositiveSmallIntegerField(default=0)),
                ('remark', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiTaskSubTask',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('assignee', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(default='未开始', max_length=40)),
                ('remark', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.multitaskmaintask')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
