# Generated by Django 5.2.15 on 2026-06-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_multitaskmaintask_multitasksubtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multitasksubtask',
            name='assignee',
        ),
    ]
